### ISSUE TITLE
How to escape quotes in LWRP's multiline patten?

### ISSUE THREAD

**Issue by z0rc** [vkhatri/chef-filebeat#74]
I need to produce the following option in prospector (note the quotes):
```
multiline:
  pattern: '^<[0-9]+>'
  negate: true
  match: after
```
So I added the following option:
```
filebeat_prospector 'test' do
  ...
  multiline 'pattern' => "'^<[0-9]+>'", 'negate' => true, 'match' => 'after'
  ...
end
```
But after chef-client run the resulting option in filebeat prospector config file looks like this: `pattern: ! '''^<[0-9]+>'''`. I also tried to escape quotes likes this: `pattern: '\'^<[0-9]+>'\'` in LWRP, this produces the same result in config file.
